"use client";

import { ArrowLeft, ArrowUpRight, Check, ChevronDown, Scale, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { LegalResponse, LawSource, Opinion } from "@/lib/legal-ai";

const loadingSteps=["質問の争点を分析","e-Govから関連法令を検索","AIが役割別に独立検討","反証担当が弱点を点検","最終判断と条文を照合"];
const providerNames:Record<Opinion["provider"],string>={openai:"GPT",anthropic:"Claude",google:"Gemini"};
const providerRoles:Record<Opinion["provider"],string>={openai:"法的要件を分解し、事実への当てはめを検討",anthropic:"例外・反対解釈・過度な断定を点検",google:"周辺法令と別の法的構成を探索"};
const conclusionNames:Record<Opinion["conclusion"],string>={likely_yes:"該当する可能性が高い",likely_no:"該当しない可能性が高い",depends:"事実関係による",insufficient:"情報不足"};

export default function LegalAiPage(){
  const [question,setQuestion]=useState("");
  const [loading,setLoading]=useState(false);
  const [activeStep,setActiveStep]=useState(0);
  const [data,setData]=useState<LegalResponse|null>(null);
  const [error,setError]=useState("");
  useEffect(()=>{if(!loading)return;const id=setInterval(()=>setActiveStep(x=>Math.min(x+1,loadingSteps.length-1)),1100);return()=>clearInterval(id)},[loading]);
  async function submit(){if(question.trim().length<5)return;setLoading(true);setActiveStep(0);setData(null);setError("");try{const response=await fetch("/api/legal-question",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({question:question.trim()})});const json=await response.json();if(!response.ok)throw new Error(json.error);setData(json)}catch(e){setError(e instanceof Error?e.message:"処理に失敗しました")}finally{setLoading(false)}}
  return <main className="min-h-screen bg-[#f3f4ef] text-[#17201d]">
    <div className="border-b border-emerald-950/10 bg-white/80 px-5 py-3 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between"><Link href="/" className="flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-emerald-800"><ArrowLeft size={16}/>Shift Gear</Link><span className="text-[10px] font-bold tracking-[.18em] text-emerald-800">LEGAL TECHNOLOGY POC</span></div></div>
    <header className="bg-gradient-to-b from-[#e3ece7] to-transparent px-5 pb-10 pt-16 text-center"><div className="mx-auto mb-5 flex size-12 items-center justify-center rounded-2xl bg-emerald-800 text-white shadow-lg shadow-emerald-900/20"><Scale size={25}/></div><h1 className="font-serif text-4xl font-bold tracking-tight sm:text-6xl">Legal Debate <i className="text-emerald-800">AI</i></h1><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-slate-600 sm:text-base">AIが役割別に検討し、反証とe-Gov法令検証を重ねて回答します。</p></header>
    <div className="mx-auto max-w-4xl px-3 pb-20 sm:px-5">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xl shadow-slate-900/5 sm:p-7"><label htmlFor="legal-question" className="font-serif text-lg font-bold">法律について質問する</label><textarea id="legal-question" value={question} onChange={e=>setQuestion(e.target.value)} rows={5} maxLength={4000} className="mt-4 w-full resize-y rounded-xl border border-slate-300 bg-slate-50 p-4 text-base leading-7 outline-none transition focus:border-emerald-700 focus:ring-4 focus:ring-emerald-800/10" placeholder="例：宅建業者ではない個人が、知人の不動産売却を繰り返し仲介して報酬を受け取ると違法ですか？"/><div className="mt-4 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-xl text-[11px] leading-5 text-slate-500">入力内容は回答生成のため外部AIサービスへ送信されます。氏名・住所・契約番号などの個人情報や機密情報は入力しないでください。</p><button onClick={submit} disabled={loading||question.trim().length<5} className="shrink-0 rounded-xl bg-emerald-800 px-5 py-3 text-sm font-bold text-white transition hover:bg-emerald-900 disabled:cursor-not-allowed disabled:opacity-40">{loading?"検討中…":"AIに質問 →"}</button></div></section>
      {loading&&<section className="mt-4 flex gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-900/5"><div className="mt-1 size-4 shrink-0 animate-pulse rounded-full bg-emerald-700 ring-8 ring-emerald-700/10"/><div><h2 className="font-bold">慎重に検討しています</h2><ol className="mt-4 space-y-2">{loadingSteps.map((step,index)=><li key={step} className={`flex items-center gap-3 text-sm ${index<=activeStep?"text-emerald-800":"text-slate-400"}`}><span className="flex size-5 items-center justify-center">{index<activeStep?<Check size={15}/>:index===activeStep?"●":"○"}</span><span className={index===activeStep?"font-bold":""}>{step}</span></li>)}</ol></div></section>}
      {error&&<div role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-800">{error}</div>}
      {data&&<Answer data={data}/>} 
    </div>
  </main>
}

function Answer({data}:{data:LegalResponse}){const answer=data.answer;const egovPoints=data.sources.length>0?40:0;const citationPoints=data.meta.verificationStatus==="pass"?25:0;const exceptionPoints=(data.debate.rebuttals.length>0||data.debate.judge.rejectedArguments.length>0||data.debate.opinions.some(opinion=>opinion.counterArguments.length>0))?15:0;const factsPoints=answer.missingFacts.length===0?10:0;const multiAiPoints=data.debate.opinions.length>=2&&data.debate.opinions.every(opinion=>opinion.conclusion===data.debate.opinions[0].conclusion)?10:0;const verificationScore=egovPoints+citationPoints+exceptionPoints+factsPoints+multiAiPoints;return <div className="mt-5 space-y-4">
  {data.meta.mockMode&&<div className="rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900"><b>Demo mode:</b> 現在はサンプルAI応答で動作しています。実APIキー設定後に本番分析へ切り替わります。</div>}
  <section className="rounded-2xl border border-slate-200 border-t-4 border-t-emerald-800 bg-white p-6 shadow-xl shadow-slate-900/5 sm:p-8"><div className="flex items-center justify-between text-[11px]"><span className="flex items-center gap-2 font-bold tracking-[.12em] text-emerald-800"><ShieldCheck size={15}/>AI法令レビュー</span><span className="text-slate-500">基準日 {data.meta.asOfDate}</span></div><h2 className="mt-7 font-serif text-lg font-bold">結論</h2><p className="mt-2 font-serif text-xl font-bold leading-9 sm:text-2xl sm:leading-10">{answer.conclusion}</p><div className="mt-6 border-y border-slate-200 py-4"><div className="flex items-end justify-between"><div><span className="text-sm font-bold text-slate-700">法令整合度</span><p className="mt-1 text-[10px] text-slate-500">法律にどの程度沿って検討できているか</p></div><b className="font-serif text-3xl text-emerald-800">{verificationScore}<span className="text-lg">%</span></b></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-gradient-to-r from-amber-500 to-emerald-700" style={{width:`${verificationScore}%`}}/></div><p className="mt-3 text-[11px] leading-5 text-slate-500">結論の正解確率ではありません。法令・条文・例外・必要事実の確認状況をもとに算出しています。</p></div><p className="mt-6 text-sm leading-7 text-slate-700 sm:text-base">{answer.explanation}</p></section>
  <Debate data={data}/>
  {answer.missingFacts.length>0&&<section className="rounded-2xl border border-amber-200 bg-white p-6"><p className="text-[10px] font-bold tracking-[.14em] text-amber-700">NEXT CHECK</p><h3 className="mt-2 font-serif text-lg font-bold">追加で確認すべき事実</h3><p className="mt-2 text-xs leading-5 text-slate-500">結論が変わる可能性があるため、次の事実を確認してください。</p><div className="mt-4 flex flex-wrap gap-2">{answer.missingFacts.map(item=><span key={item} className="rounded-full bg-amber-100 px-3 py-2 text-xs font-medium text-amber-900">{item}</span>)}</div></section>}
  <div className="text-center text-[11px] text-slate-500">成功: {data.meta.providersSucceeded.join(" / ")} · 検証: {data.meta.verificationStatus.toUpperCase()} · {(data.meta.durationMs/1000).toFixed(1)}秒</div>
  <aside className="rounded-xl border border-stone-300 bg-stone-200/70 p-4 text-xs leading-6 text-slate-600"><b className="mr-2 text-slate-900">ご注意</b>{answer.disclaimer}</aside>
  <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold tracking-[.14em] text-emerald-700">PRIMARY SOURCES</p><h3 className="mt-2 font-serif text-lg font-bold">根拠法令</h3></div><span className="text-xs text-slate-500">{data.sources.length} sources</span></div>{data.sources.length>0?<div className="mt-4 space-y-3">{data.sources.map((source,index)=><Source source={source} key={`${source.lawId}-${index}`}/>)}</div>:<p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-900">今回の回答ではe-Govの根拠条文を取得できませんでした。断定せず、専門家または法令原文をご確認ください。</p>}</section>
</div>}

function Debate({data}:{data:LegalResponse}){const judge=data.debate.judge;return <details className="group overflow-hidden rounded-2xl border border-slate-200 bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-6"><div><p className="text-[10px] font-bold tracking-[.14em] text-indigo-700">AI DEBATE</p><b className="mt-2 block font-serif text-lg">AIの討論の過程を見る</b><p className="mt-1 text-xs text-slate-500">分析役の発言 → 反証役の指摘 → Judgeの最終判定</p></div><ChevronDown className="shrink-0 transition group-open:rotate-180" size={20}/></summary><div className="border-t border-slate-200 bg-slate-50/70 p-4 sm:p-6">
  <div className="relative space-y-7 before:absolute before:bottom-8 before:left-4 before:top-8 before:w-px before:bg-slate-200 sm:before:left-5">
    {data.debate.opinions.map(opinion=><div key={opinion.provider} className="relative flex items-start gap-3 sm:gap-4"><span className="z-10 flex size-8 shrink-0 items-center justify-center rounded-full bg-indigo-700 text-xs font-bold text-white ring-4 ring-slate-50 sm:size-10">{providerNames[opinion.provider].slice(0,1)}</span><article className="min-w-0 flex-1 rounded-2xl rounded-tl-sm border border-indigo-100 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{providerNames[opinion.provider]}</b><span className="rounded-full bg-indigo-50 px-2 py-1 text-[10px] font-bold text-indigo-700">分析役</span></div><p className="mt-1 text-[11px] text-slate-500">{providerRoles[opinion.provider]}</p><p className="mt-3 text-sm leading-7 text-slate-800">「{opinion.summary}」</p><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">{conclusionNames[opinion.conclusion]}</span></div>{opinion.reasoning.length>0&&<details className="mt-3 border-t border-slate-100 pt-3"><summary className="cursor-pointer text-xs font-bold text-indigo-700">発言の根拠を見る</summary><ol className="mt-2 list-decimal space-y-1 pl-5 text-xs leading-6 text-slate-600">{opinion.reasoning.map(reason=><li key={reason}>{reason}</li>)}</ol></details>}</article></div>)}
    {data.debate.rebuttals.flatMap((rebuttal,index)=>rebuttal.issues.map((issue,issueIndex)=><div key={`${rebuttal.provider}-${index}-${issueIndex}`} className="relative flex items-start gap-3 sm:gap-4"><span className="z-10 flex size-8 shrink-0 items-center justify-center rounded-full bg-amber-500 text-white ring-4 ring-slate-50 sm:size-10">↪</span><article className="min-w-0 flex-1 rounded-2xl rounded-tl-sm border border-amber-200 bg-amber-50 p-4 shadow-sm"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{providerNames[rebuttal.provider as Opinion["provider"]]||rebuttal.provider}</b><span className="rounded-full bg-amber-200 px-2 py-1 text-[10px] font-bold text-amber-900">反証役</span><span className="text-[10px] text-slate-500">→ {providerNames[issue.targetProvider as Opinion["provider"]]||issue.targetProvider}への指摘</span></div><p className="mt-3 text-sm leading-7 text-slate-800">「{issue.explanation}」</p></article></div>))}
    {data.debate.rebuttals.length===0&&<div className="relative flex items-start gap-3 sm:gap-4"><span className="z-10 flex size-8 shrink-0 items-center justify-center rounded-full bg-amber-500 text-white ring-4 ring-slate-50 sm:size-10">↪</span><div className="flex-1 rounded-2xl rounded-tl-sm border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><b>反証役</b><p className="mt-2">独立した別AIからの指摘はありません。分析役が自身の発言を再点検しました。</p></div></div>}
    <div className="relative flex items-start gap-3 sm:gap-4"><span className="z-10 flex size-8 shrink-0 items-center justify-center rounded-full bg-emerald-700 text-xs font-bold text-white ring-4 ring-slate-50 sm:size-10">J</span><article className="min-w-0 flex-1 rounded-2xl rounded-tl-sm border border-emerald-200 bg-emerald-50 p-4 shadow-sm"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">Judge</b><span className="rounded-full bg-emerald-200 px-2 py-1 text-[10px] font-bold text-emerald-900">統合・最終判定役</span></div><p className="mt-3 text-sm font-medium leading-7 text-emerald-950">「{judge.shortAnswer}」</p>{judge.issues.length>0&&<details className="mt-3 border-t border-emerald-200 pt-3"><summary className="cursor-pointer text-xs font-bold text-emerald-800">判定の理由を見る</summary><div className="mt-2 space-y-2">{judge.issues.map(item=><div key={item.issue} className="rounded-lg bg-white/80 p-3"><b className="text-xs">{item.issue}</b><p className="mt-1 text-xs leading-5 text-slate-600">{item.analysis}</p></div>)}</div></details>}</article></div>
  </div>
</div></details>}

function Source({source}:{source:LawSource}){return <article className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between gap-4"><span className="text-[10px] font-bold tracking-[.12em] text-emerald-800">e-Gov 一次情報</span><a href={source.sourceUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-xs font-bold text-emerald-800">原文を開く <ArrowUpRight size={13}/></a></div><h4 className="mt-3 font-bold">{source.lawName} {source.article&&<small className="ml-2 text-xs font-medium text-slate-500">{source.article}</small>}</h4>{source.lawNumber&&<p className="mt-1 text-[11px] text-slate-500">{source.lawNumber}</p>}<p className="mt-3 line-clamp-6 whitespace-pre-wrap text-xs leading-6 text-slate-600">{source.text}</p></article>}
