"use client";

import { ArrowLeft, ArrowUpRight, Check, ChevronDown, Scale, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { LegalResponse, LawSource, Opinion } from "@/lib/legal-ai";

const loadingSteps=["質問の争点を分析","e-Govから関連法令を検索","3つのAIが独立検討","AI同士で相互反証","最終判断と条文を照合"];
const providerNames:Record<Opinion["provider"],string>={openai:"GPT",anthropic:"Claude",google:"Gemini"};

export default function LegalAiPage(){
  const [question,setQuestion]=useState("");
  const [loading,setLoading]=useState(false);
  const [activeStep,setActiveStep]=useState(0);
  const [data,setData]=useState<LegalResponse|null>(null);
  const [error,setError]=useState("");
  useEffect(()=>{if(!loading)return;const id=setInterval(()=>setActiveStep(x=>Math.min(x+1,loadingSteps.length-1)),1100);return()=>clearInterval(id)},[loading]);
  async function submit(){if(question.trim().length<5)return;setLoading(true);setActiveStep(0);setData(null);setError("");try{const response=await fetch("/api/legal-question",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({question:question.trim()})});const json=await response.json();if(!response.ok)throw new Error(json.error);setData(json)}catch(e){setError(e instanceof Error?e.message:"処理に失敗しました")}finally{setLoading(false)}}
  return <main className="min-h-screen bg-[#f3f4ef] text-[#17201d]">
    <div className="border-b border-emerald-950/10 bg-white/80 px-5 py-3 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between"><Link href="/" className="flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-emerald-800"><ArrowLeft size={16}/>Shift Gear</Link><span className="text-[10px] font-bold tracking-[.18em] text-emerald-800">LEGAL TECHNOLOGY POC</span></div></div>
    <header className="bg-gradient-to-b from-[#e3ece7] to-transparent px-5 pb-10 pt-16 text-center"><div className="mx-auto mb-5 flex size-12 items-center justify-center rounded-2xl bg-emerald-800 text-white shadow-lg shadow-emerald-900/20"><Scale size={25}/></div><h1 className="font-serif text-4xl font-bold tracking-tight sm:text-6xl">Legal Debate <i className="text-emerald-800">AI</i></h1><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-slate-600 sm:text-base">複数AIが独立検討し、反証とe-Gov法令検証を重ねて回答します。</p></header>
    <div className="mx-auto max-w-4xl px-3 pb-20 sm:px-5">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-xl shadow-slate-900/5 sm:p-7"><label htmlFor="legal-question" className="font-serif text-lg font-bold">法律について質問する</label><textarea id="legal-question" value={question} onChange={e=>setQuestion(e.target.value)} rows={5} maxLength={4000} className="mt-4 w-full resize-y rounded-xl border border-slate-300 bg-slate-50 p-4 text-base leading-7 outline-none transition focus:border-emerald-700 focus:ring-4 focus:ring-emerald-800/10" placeholder="例：宅建業者ではない個人が、知人の不動産売却を繰り返し仲介して報酬を受け取ると違法ですか？"/><div className="mt-4 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-xl text-[11px] leading-5 text-slate-500">入力内容は回答生成のため外部AIサービスへ送信されます。氏名・住所・契約番号などの個人情報や機密情報は入力しないでください。</p><button onClick={submit} disabled={loading||question.trim().length<5} className="shrink-0 rounded-xl bg-emerald-800 px-5 py-3 text-sm font-bold text-white transition hover:bg-emerald-900 disabled:cursor-not-allowed disabled:opacity-40">{loading?"検討中…":"3つのAIに質問 →"}</button></div></section>
      {loading&&<section className="mt-4 flex gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-900/5"><div className="mt-1 size-4 shrink-0 animate-pulse rounded-full bg-emerald-700 ring-8 ring-emerald-700/10"/><div><h2 className="font-bold">慎重に検討しています</h2><ol className="mt-4 space-y-2">{loadingSteps.map((step,index)=><li key={step} className={`flex items-center gap-3 text-sm ${index<=activeStep?"text-emerald-800":"text-slate-400"}`}><span className="flex size-5 items-center justify-center">{index<activeStep?<Check size={15}/>:index===activeStep?"●":"○"}</span><span className={index===activeStep?"font-bold":""}>{step}</span></li>)}</ol></div></section>}
      {error&&<div role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-800">{error}</div>}
      {data&&<Answer data={data}/>} 
    </div>
  </main>
}

function Answer({data}:{data:LegalResponse}){const answer=data.answer;return <div className="mt-5 space-y-4">
  {data.meta.mockMode&&<div className="rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900"><b>Demo mode:</b> 現在はサンプルAI応答で動作しています。実APIキー設定後に本番分析へ切り替わります。</div>}
  <section className="rounded-2xl border border-slate-200 border-t-4 border-t-emerald-800 bg-white p-6 shadow-xl shadow-slate-900/5 sm:p-8"><div className="flex items-center justify-between text-[11px]"><span className="flex items-center gap-2 font-bold tracking-[.12em] text-emerald-800"><ShieldCheck size={15}/>検証済み回答</span><span className="text-slate-500">基準日 {data.meta.asOfDate}</span></div><h2 className="mt-7 font-serif text-lg font-bold">結論</h2><p className="mt-2 font-serif text-xl font-bold leading-9 sm:text-2xl sm:leading-10">{answer.conclusion}</p><div className="mt-6 border-y border-slate-200 py-4"><div className="flex justify-between text-sm"><span className="text-slate-500">確信度</span><b className="text-emerald-800">{Math.round(answer.confidence*100)}%</b></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-gradient-to-r from-amber-500 to-emerald-700" style={{width:`${answer.confidence*100}%`}}/></div><p className="mt-2 text-[11px] text-slate-500">e-Gov一次情報との整合性を含むAI評価</p></div><p className="mt-6 text-sm leading-7 text-slate-700 sm:text-base">{answer.explanation}</p></section>
  <div className="grid gap-4 sm:grid-cols-2"><Info title="重要な争点" items={answer.keyIssues} ordered/><Info title="反対解釈・例外" items={answer.counterView}/></div>
  {answer.missingFacts.length>0&&<section className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-serif font-bold">追加で確認すべき事実</h3><div className="mt-4 flex flex-wrap gap-2">{answer.missingFacts.map(item=><span key={item} className="rounded-full bg-amber-100 px-3 py-2 text-xs font-medium text-amber-900">{item}</span>)}</div></section>}
  <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h3 className="font-serif text-lg font-bold">根拠法令</h3><span className="text-xs text-slate-500">{data.sources.length} sources</span></div><div className="mt-4 space-y-3">{data.sources.map((source,index)=><Source source={source} key={`${source.lawId}-${index}`}/>)}</div></section>
  <details className="group overflow-hidden rounded-2xl border border-slate-200 bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-6"><div><b>AI討論の過程を見る</b><p className="mt-1 text-xs text-slate-500">{data.debate.opinions.length}つの独立見解と{data.debate.rebuttals.length}つの反証</p></div><ChevronDown className="transition group-open:rotate-180" size={20}/></summary><div className="space-y-4 border-t border-slate-200 p-6">{data.debate.opinions.map(opinion=><article key={opinion.provider} className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between"><b>{providerNames[opinion.provider]}の見解</b><span className="text-xs font-bold text-emerald-800">{Math.round(opinion.confidence*100)}%</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{opinion.summary}</p></article>)}{data.debate.rebuttals.length>0&&<div><h4 className="font-bold">相互反証で見つかった論点</h4>{data.debate.rebuttals.flatMap(x=>x.issues).map((issue,index)=><p key={index} className="mt-2 border-l-2 border-amber-500 bg-amber-50 p-3 text-sm leading-6"><b className="mr-2 text-[10px] text-amber-800">{issue.severity.toUpperCase()}</b>{issue.explanation}</p>)}</div>}<div className="rounded-xl bg-emerald-50 p-4"><b>Judgeの判断</b><p className="mt-2 text-sm leading-6">{data.debate.judge.shortAnswer}</p></div></div></details>
  <div className="text-center text-[11px] text-slate-500">成功: {data.meta.providersSucceeded.join(" / ")} · 検証: {data.meta.verificationStatus.toUpperCase()} · {(data.meta.durationMs/1000).toFixed(1)}秒</div>
  <aside className="rounded-xl border border-stone-300 bg-stone-200/70 p-4 text-xs leading-6 text-slate-600"><b className="mr-2 text-slate-900">ご注意</b>{answer.disclaimer}</aside>
</div>}

function Info({title,items,ordered=false}:{title:string;items:string[];ordered?:boolean}){const Tag=ordered?"ol":"ul";return <section className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-serif font-bold">{title}</h3><Tag className={`mt-4 space-y-3 text-sm leading-6 text-slate-700 ${ordered?"list-decimal pl-5":"list-disc pl-5"}`}>{items.map(item=><li key={item}>{item}</li>)}</Tag></section>}
function Source({source}:{source:LawSource}){return <article className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between gap-4"><span className="text-[10px] font-bold tracking-[.12em] text-emerald-800">e-Gov 一次情報</span><a href={source.sourceUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-xs font-bold text-emerald-800">原文を開く <ArrowUpRight size={13}/></a></div><h4 className="mt-3 font-bold">{source.lawName} {source.article&&<small className="ml-2 text-xs font-medium text-slate-500">{source.article}</small>}</h4>{source.lawNumber&&<p className="mt-1 text-[11px] text-slate-500">{source.lawNumber}</p>}<p className="mt-3 line-clamp-6 whitespace-pre-wrap text-xs leading-6 text-slate-600">{source.text}</p></article>}
